/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

package com.mycompany.prog6112ice2;

/**
 *
 * @author maist
 */
public class Salesagent extends Employee implements IVehicleDealer {


// Threshold for the "Top Seller!" recognition, in Rand.
    private static final double TOP_SELLER_THRESHOLD = 10000;
 
    // ----- Additional attributes -----
    private int vehiclesSold;
    private double commissionRate; // e.g. 0.05 for 5%

/**
     * Constructor for SalesAgent.
     * @param name           the agent's name
     * @param employeeId     the agent's unique ID
     * @param baseSalary     the agent's base salary
     * @param vehiclesSold   number of vehicles sold by the agent
     * @param commissionRate commission rate per vehicle sold (as a decimal, e.g. 0.05)
     */
    public Salesagent(String name, String employeeId, double baseSalary,
                       int vehiclesSold, double commissionRate) {
        super(name, employeeId, baseSalary);
        this.vehiclesSold = vehiclesSold;
        this.commissionRate = commissionRate;
    }
 
    // ----- Getters -----
    public int getVehiclesSold() {
        return vehiclesSold;
    }
 
    public double getCommissionRate() {
        return commissionRate;
    }
 
    /**
     * Implements the abstract method from Employee.
     * Commission is calculated as: vehiclesSold * baseSalary * commissionRate
     * (assumes commission accrues per vehicle, scaled by base salary and rate).
     * @return the calculated commission.
     */
    public double calculateCommission() {
    int baseSalary = 0;
        return vehiclesSold * baseSalary * commissionRate;
    }
 
    /**
     * Implements the IVehicleDealer interface method.
     * Generates a simple quote summary for the agent.
     * @return a String containing the quote details.
     */
    public String generateQuote() {
    String employeeId = null;
    String name = null;
        return "Quote generated by " + name + " (ID: " + employeeId + ") - "
                + vehiclesSold + " vehicle(s) sold at a commission rate of "
                + (commissionRate * 100) + "%.";
    }
 
    /**
     * Calculates the agent's total earnings (base salary + commission).
     * @return the total earnings.
     */
    public double getTotalEarnings() {
    double baseSalary = 0;
        return baseSalary + calculateCommission();
    }
 
    /**
     * Prints a full report of the agent's details and earnings to the console.
     * Highlights the agent as a "Top Seller!" if their commission
     * earnings exceed R10 000.
     */
    public void printReport() {
        double commission = calculateCommission();
        double totalEarnings = getTotalEarnings();
 
        System.out.println("---------------------------------------------");
    String name = null;
        System.out.println("Agent Name     : " + name);
    String employeeId = null;
        System.out.println("Employee ID    : " + employeeId);
    Object[] baseSalary = null;
        System.out.printf ("Base Salary    : R%,.2f%n", baseSalary);
        System.out.println("Vehicles Sold  : " + vehiclesSold);
        System.out.printf ("Commission     : R%,.2f%n", commission);
        System.out.printf ("Total Earnings : R%,.2f%n", totalEarnings);
 
        if (commission > TOP_SELLER_THRESHOLD) {
            System.out.println(">>> Top Seller! <<<");
        }
        System.out.println("---------------------------------------------");
    }
}